### ISSUE TITLE
All error messages.

### ISSUE THREAD

**Issue by jmw999** [aknutas/nails#10]
Hello,

Great sounding project but although I thought I had followed the instructions for the Hammer analysis all I'm getting back is 'invalid' or 'not found'  error messages. Any idea what I'm doing wrong?

**Comment by jsalminen** [comment]
Hi,

Sorry for the delayed reply. Without seeing the data sample it is hard to say what has gone wrong. First I would ensure that data has been downloaded in correct format from Web of Science (Core Collection selected from drop down menu before searching data, Tab delimited (Mac) or Tab delimited (Win) format,  Full Record and Cited References). 

If that does not work, could you send us a copy of the dataset that caused the problems so we can investigate what went wrong?

Best,
Juho
