### ISSUE TITLE
Error in cleaning2

### ISSUE THREAD

**Issue by NanisTe** [aknutas/nails#11]
I get the following error in cleaning2

`Error in names(literature) <- data.names : 'names' attribute [2] must be the same length as the vector [0]`

when I try to run the exploration markdown.

**Comment by NanisTe** [comment]
One has to delete the readme file first. Maybe one exclude the readme file from the input list in code or write a comment in the main exploration script.

**Comment by aknutas** [comment]
Thanks for the feedback! We addressed this in commit 5a6cebe0d6dea8eb82582e6a087c7ee5b55755fc by adding skip check.
