### ISSUE TITLE
Endnote

### ISSUE THREAD

**Issue by RussellButson** [aknutas/nails#19]
Is it possible to use Endnote exported data or only Web of science Tab Delimited format?

Tab Delimited style | .txt format.  

R

**Comment by jsalminen** [comment]
Not at the moment, but that's a good idea! We'll consider adding support in the future.

Juho

**Comment by RussellButson** [comment]
Hi Juho,

I am only suggesting this as hammer would be great for a post-selection/analysis review. My main interests in the details of article data of lit. datasets concerns articles already selected as useful (already screened and selected).

Russell

**Comment by aknutas** [comment]
Hi,
   thanks for the development ideas. We're currently refactoring for a 2.0 release and after that we'll think of implementing new features. The main issue is that most reference managers and scientific databases do not export lists of references, which makes network analysis impossible. In the far future we might implement analysis variants depending on input sources.

Best,
   Antti Knutas

**Comment by RussellButson** [comment]
Hi Antti,

Understand and thank you for the update.

They do produce report lists in rtf.

Russell
