### ISSUE TITLE
Import other databases file formats

### ISSUE THREAD

**Issue by mcd92** [aknutas/nails#20]
Dear developers,

I´m trying to write an Systematic Literature Review with more than one database (besides Web of Science, I want to review Science Direct, Emerald, Scopus and IEEE, for example). I like the analisys run by Nails very much, but I would like to include those other databases as well. Is there a way to convert other source's file formats so they can be also imported by Nails? If not, I will leave the suggestion here. Even if it were only the BibTex format, as most databases researches can be exported to .bib.

Thank you very much for your work!

Apolo

**Comment by aknutas** [comment]
Hi,
   thanks for the development ideas. We're currently refactoring for a 2.0 release and after that we'll think of implementing new features. The main issue is that most reference managers and scientific databases do not export lists of references, which makes network analysis impossible. We were also investigating Scopus data when originally developing nails.

In the far future we might implement analysis variants depending on input sources, with more limited reports produced when analyzing less rich data.

Best,
   Antti Knutas
