### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by booka5838** [aknutas/nails#21]
Hi,

I keep trying to access your nails project using the link below.
http://hammer.nailsproject.net/
Whenever I click the link the attached error message appears.

![nails project issue](https://user-images.githubusercontent.com/30541796/28741596-68deedee-744c-11e7-9190-2c3368519399.JPG)

Is this occurring for anyone else?  
Do you know why this is occurring?

Any help would be much appreciated.
Thanks

**Comment by aknutas** [comment]
Server issue, rebooted.
