### ISSUE TITLE
can't reach HAMMER sever

### ISSUE THREAD

**Issue by EcoGeographer** [aknutas/nails#24]
First: Your HAMMER service is awesome. Thanks for the work.
But I can’t reach the page since a few days. Tried different browser (Firefox, Chrome, IE) and different IPs. Can’t figure out if the problem is on my site. Maybe something is wrong with the server?

**Comment by horgag1** [comment]
I'm having the same problem!

**Comment by aknutas** [comment]
The server is unreachable. I have opened a support ticket with our cloud administration.

**Comment by aknutas** [comment]
The virtual machine server was re-started by the university IT admins. Everything should be now operational.
