### ISSUE TITLE
Same error list like #25

### ISSUE THREAD

**Issue by vollm** [aknutas/nails#27]
I tried to use the http://hammer.nailsproject.net/ service and got the same error list like issue #25. I followed the instructions and used this dataset 
[Archiv.zip](https://github.com/aknutas/nails/files/2005640/Archiv.zip)

Hopefully you can help me cause I would really like to use that great service. 

Thanks!

**Comment by snied** [comment]
Hi vollm,

I experienced the same issue. However, for me it worked to download the file with the file format **Tab-delimited (Win, UTF-8)** from WoS. Maybe it also works for you as well.

Cheers
snied

**Comment by sorayarp** [comment]
Hi!

I have the same error list (#25).  I have followed the instructions and even I have tried with the file format Tab delimited (Win, UTF-8).  Any suggestion?

Thank you!

**Comment by aknutas** [comment]
Web of Science changed their csv export format again. We do not currently have the resources to rewrite the input and processing part of our service.
