### ISSUE TITLE
The WoS export format has been changed, causing problems with R script ingestion

### ISSUE THREAD

**Issue by aknutas** [aknutas/nails#3]
The R scripts have problems in ingesting the new tab-delimited format.

**Comment by aknutas** [comment]
Fix is ongoing.

**Comment by aknutas** [comment]
Fault found: WoS added two new columns to export format that have no headers (which causes an exception in R data import library)

**Comment by aknutas** [comment]
The issue with headers have been fix, but the fundamental problem is that the new export format by WoS does not match their documentation ( http://images.webofknowledge.com/WOK46/help/WOS/h_fieldtags.html ). The issue has been reported to Web of Science.

**Comment by aknutas** [comment]
Commit https://github.com/aknutas/nails/commit/4fd8e6372a7511f00898c0876a2a2b16b8cf6e54 fixes the issue. R script has been updated to the HAMMER server.

**Comment by risingrohini** [comment]
Unable to import the data from WoS. Gives an error :

![image](https://user-images.githubusercontent.com/51747321/59518293-fe06cb80-8e8a-11e9-84b3-20edf50a6d12.png)
