### ISSUE TITLE
I can not access for the link "http://hammer.nailsproject.net/"

### ISSUE THREAD

**Issue by qusay81** [aknutas/nails#31]
Hello Sir, 

I have been tried much time to access to this link "http://hammer.nailsproject.net/" but no way, I do not if the server is down or What?

**Comment by aknutas** [comment]
Regrettably we are no longer able to maintain this service.

**Comment by qusay81** [comment]
Thanks, Sir for your answer, but not other software can use that it can do the same job?
My Regards

**Comment by aknutas** [comment]
Instructions for the offline versions are available at https://sites.google.com/site/bibliometricdatavisualization/instructions
