### ISSUE TITLE
HAMMER error messages

### ISSUE THREAD

**Issue by janeyat** [aknutas/nails#7]
Could you look at my results at http://hammer.nailsproject.net/analyses/304?akey=GuiIzAzDogqJqueU 

There are many weird error messages that I do not understand and I wonder how they are affecting the ouput from HAMMER. I meticulously collected the data from WOS to make sure I did that part correctly and re-ran HAMMER with the same error messages.

When I truncated the data set by excluding ten years of publication (original set included twenty years of publication (1996-2015; I then excluded 1996-2005) and re-ran in HAMMER I did not get any errors. 

Thanks,
Jane

P.S. I am now reading your article "Cloud Based Bibliometric Analysis Service for Systematic Mapping Studies" to see if the cross multiplication is explained there.

**Comment by jsalminen** [comment]
Hi Jane,

Can you send us the data that caused the error messages? I could check what is going on.

Best,
Juho

**Comment by janeyat** [comment]
Here it is. Thank you for checking into this.

[Anthrozoos1996-2015_WOS.zip](https://github.com/aknutas/nails/files/514545/Anthrozoos1996-2015_WOS.zip)

**Comment by jsalminen** [comment]
Thanks! I'll see what I can do.

**Comment by jsalminen** [comment]
Hi Jane! Sorry for the delay. I fixed the bug and updated the source code on GitHub. It should work now on your data too: [report.](https://dl.dropboxusercontent.com/u/13579699/Anthrozoos2006-15.html). We'll update the app also soon. I also added a chart in the end of the report showing the most commonly appearing publication names in article references. Is that what you had in mind?

Best,
Juho

**Comment by jsalminen** [comment]
The app is now up to date too.

**Comment by janeyat** [comment]
Oh, thank you for doing that. I appreciate it. I was recently reading something bibliometrics-related about how you DON'T want just straight numbers for citation (where on earth was I reading that?!!)--that you want to weight the cited journals using a formual....so I'm sure you've done it the correct way, LOL. Nevertheless, I like being able to see the straight numbers.
